version: '3.8'

services:
  web:
    image: project-ps :latest  
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.project-ps.rule=Host(`project-ps.local`)"
      - "traefik.http.services.project-ps.loadbalancer.server.port=5000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: rishi
      POSTGRES_PASSWORD: 1234
    networks:
      - app-network

networks:
  app-network:
networks:
  app-network:
    external: true
