[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[api]
  insecure = true
  dashboard = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

[file]

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    swarmMode = true
    exposedByDefault = false

[log]
  level = "INFO"

[accessLog]
